// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOigE5wzwz5wuBvS91e5t-9991WQPpoS8',
    appId: '1:147473518773:web:7eadfbec99d5537536eefc',
    messagingSenderId: '147473518773',
    projectId: 'sangkuriang-f32f9',
    authDomain: 'sangkuriang-f32f9.firebaseapp.com',
    storageBucket: 'sangkuriang-f32f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2XzID5OKL330kDShHo0Et-JBIsttTrE',
    appId: '1:147473518773:android:79e833aeeafc471b36eefc',
    messagingSenderId: '147473518773',
    projectId: 'sangkuriang-f32f9',
    storageBucket: 'sangkuriang-f32f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYjkPZVu5ifMGqHTE36YjYBwKA8OTQjds',
    appId: '1:147473518773:ios:548667d016d8201336eefc',
    messagingSenderId: '147473518773',
    projectId: 'sangkuriang-f32f9',
    storageBucket: 'sangkuriang-f32f9.appspot.com',
    iosBundleId: 'com.example.sangkuriang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYjkPZVu5ifMGqHTE36YjYBwKA8OTQjds',
    appId: '1:147473518773:ios:8827f3860703c68c36eefc',
    messagingSenderId: '147473518773',
    projectId: 'sangkuriang-f32f9',
    storageBucket: 'sangkuriang-f32f9.appspot.com',
    iosBundleId: 'com.example.sangkuriang.RunnerTests',
  );
}
